function [E, Eh] = hex2edge(H)
Eh = [H(:,1),H(:,2);...
    H(:,2),H(:,3); ...
    H(:,3),H(:,4); ...
    H(:,4),H(:,1); ...
    H(:,5),H(:,1); ...
    H(:,8),H(:,5); ...
    H(:,4),H(:,8); ...
    H(:,6),H(:,5); ...
    H(:,7),H(:,6); ...
    H(:,7),H(:,8); ...
    H(:,3),H(:,7); ...
    H(:,2),H(:,6)];
IEh = repmat((1:size(H,1))',12,1); %indexing for E in terms of H
[~,ia,ib] = unique(sort(Eh,2),'rows'); 
%ia is the index of F in terms of uniqueF; ib is the inverse;
E = Eh(ia, :);
HuniqueE = IEh(ia, :); %where uniqueF is in terms of H (one of the face)
%find the other index for uniqueF
end
%F = uniqueF(ib,:)
%unique facelist
%output 2 indices
